import type { Dispatch, SetStateAction } from "react";
import type { ExamSet, Subject } from "@/lib/api/question-import-client";

type Props = { subjects: Subject[]; examSets: ExamSet[]; subjectId: string; examSetIds: string[]; format: "json" | "structured_text"; duplicatePolicy: "reject" | "skip" | "allow"; defaultStatus: "draft" | "published"; defaultDifficulty?: "easy" | "medium" | "hard"; defaultTranslationStatus?: "not_required" | "pending" | "translated" | "reviewed" | "failed"; isLoadingSubjects: boolean; isLoadingExamSets: boolean; isConfirming: boolean; setSubject: (value: string) => void; setExamSetIds: Dispatch<SetStateAction<string[]>>; setFormat: (value: "json" | "structured_text") => void; setDuplicatePolicy: (value: "reject" | "skip" | "allow") => void; setDefaultStatus: (value: "draft" | "published") => void; setDefaultDifficulty: (value: "easy" | "medium" | "hard" | undefined) => void; setDefaultTranslationStatus: (value: "not_required" | "pending" | "translated" | "reviewed" | "failed") => void };

export function ImportConfiguration(props: Props) {
  const toggleExamSet = (id: string) => props.setExamSetIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <section className="import-config-card"><div className="import-section-heading"><div><p className="eyebrow">Step 1</p><h2>Import configuration</h2></div><span className="import-status" aria-live="polite">Not validated</span></div><div className="import-form-grid">
    <label>Subject<select value={props.subjectId} disabled={props.isLoadingSubjects || props.isConfirming} onChange={(event) => props.setSubject(event.target.value)}><option value="">Select a subject</option>{props.subjects.map((item) => <option key={item._id} value={item._id}>{item.code} — {item.name}</option>)}</select></label>
    <fieldset><legend>Target exam sets <small>optional</small></legend><div className="exam-set-options">{props.isLoadingExamSets ? <p className="field-hint">Loading exam sets…</p> : props.examSets.length ? props.examSets.map((item) => <label className="check-option" key={item._id}><input type="checkbox" checked={props.examSetIds.includes(item._id)} disabled={props.isConfirming} onChange={() => toggleExamSet(item._id)} /><span>{item.title}</span><small>{item.questionCount} questions · {item.status}</small></label>) : <p className="field-hint">{props.subjectId ? "No active exam sets. Questions will be stored in the shared bank." : "Select a subject first."}</p>}</div></fieldset>
    <label>Input format<select value={props.format} disabled={props.isConfirming} onChange={(event) => props.setFormat(event.target.value as "json" | "structured_text")}><option value="json">JSON</option><option value="structured_text">Structured text</option></select></label>
    <label>Duplicate policy<select value={props.duplicatePolicy} disabled={props.isConfirming} onChange={(event) => props.setDuplicatePolicy(event.target.value as "reject" | "skip" | "allow")}><option value="reject">Reject duplicates</option><option value="skip">Skip duplicates</option><option value="allow">Allow duplicates</option></select></label>
    <label>Default status<select value={props.defaultStatus} disabled={props.isConfirming} onChange={(event) => props.setDefaultStatus(event.target.value as "draft" | "published")}><option value="draft">Draft</option><option value="published">Published</option></select></label>
    <label>Default difficulty<select value={props.defaultDifficulty ?? ""} disabled={props.isConfirming} onChange={(event) => props.setDefaultDifficulty((event.target.value || undefined) as "easy" | "medium" | "hard" | undefined)}><option value="">Not set</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label>
    <label>Default translation status<select value={props.defaultTranslationStatus ?? "not_required"} disabled={props.isConfirming} onChange={(event) => props.setDefaultTranslationStatus(event.target.value as "not_required" | "pending" | "translated" | "reviewed" | "failed")}><option value="not_required">Not required</option><option value="pending">Pending</option><option value="translated">Translated</option><option value="reviewed">Reviewed</option><option value="failed">Failed</option></select></label>
  </div></section>;
}
