import type { AttemptQuestion } from "@/lib/api/exam-attempt-client";

function Localized({ text, showTranslation }: { text: { original: string; vi?: string }; showTranslation: boolean }) { return <>{text.original}{showTranslation && text.vi ? <span className="translation">{text.vi}</span> : null}</>; }

export function QuestionRenderer({ question, answer, showTranslation, disabled, onAnswer }: { question: AttemptQuestion; answer: { selectedOptionIds?: string[]; statementAnswers?: Array<{ statementId: string; answer: boolean }> }; showTranslation: boolean; disabled: boolean; onAnswer: (value: { selectedOptionIds?: string[]; statementAnswers?: Array<{ statementId: string; answer: boolean }> }) => void }) {
  const selected = answer.selectedOptionIds ?? [];
  if (question.type === "true_false_group") return <fieldset className="question-fieldset"><legend className="question-text"><Localized text={question.content} showTranslation={showTranslation} /></legend><div className="statements">{question.statements?.map((statement) => { const current = answer.statementAnswers?.find((item) => item.statementId === statement.id)?.answer; return <div className="statement-row" key={statement.id}><span><Localized text={statement.content} showTranslation={showTranslation} /></span><div className="tf-options">{[[true, "True"], [false, "False"]].map(([value, label]) => <label key={String(value)}><input type="radio" name={statement.id} disabled={disabled} checked={current === value} onChange={() => onAnswer({ statementAnswers: [...(answer.statementAnswers ?? []).filter((item) => item.statementId !== statement.id), { statementId: statement.id, answer: value as boolean }] })} />{label}</label>)}</div>{current === undefined && <small>Not answered</small>}</div>; })}</div></fieldset>;
  const multiple = question.type === "multiple_choice";
  return <fieldset className="question-fieldset"><legend className="question-text"><Localized text={question.content} showTranslation={showTranslation} /></legend><div className="answer-options">{question.options?.map((option) => <label className="answer-option" key={option.id}><input type={multiple ? "checkbox" : "radio"} name={question.questionId} disabled={disabled} checked={selected.includes(option.id)} onChange={() => onAnswer({ selectedOptionIds: multiple ? (selected.includes(option.id) ? selected.filter((id) => id !== option.id) : [...selected, option.id]) : [option.id] })} /><span className="option-label">{option.label}</span><span><Localized text={option.content} showTranslation={showTranslation} /></span></label>)}</div></fieldset>;
}
